;;; dawnfox-theme.el --- Dawnfox light theme (Nightfox family port) -*- lexical-binding: t; -*-

;;; Port of EdenEast/nightfox.nvim's Dawnfox palette (light variant).
;;; Colors from lua/nightfox/palette/dawnfox.lua upstream.

(deftheme dawnfox "Nightfox family (nvim port): Dawnfox light.")

(custom-theme-set-faces 'dawnfox
 '(default ((t (:background "#faf4ed" :foreground "#575279"))))
 '(cursor ((t (:background "#907aa9"))))
 '(region ((t (:background "#d0d8d8" :foreground "#625c87"))))
 '(hl-line ((t (:background "#ebdfe4"))))
 '(line-number ((t (:background "#faf4ed" :foreground "#a8a3b3"))))
 '(line-number-current-line ((t (:background "#ebdfe4" :foreground "#575279"))))
 '(fringe ((t (:background "#faf4ed" :foreground "#a8a3b3"))))
 '(vertical-border ((t (:background "#faf4ed" :foreground "#bdbfc9"))))
 '(window-divider ((t (:foreground "#bdbfc9"))))
 '(shadow ((t (:foreground "#a8a3b3"))))
 '(minibuffer-prompt ((t (:foreground "#4c4769"))))
 '(error ((t (:foreground "#b4637a"))))
 '(warning ((t (:foreground "#ea9d34"))))
 '(success ((t (:foreground "#618774"))))
 '(font-lock-comment-face ((t (:foreground "#9893a5"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9893a5"))))
 '(font-lock-doc-face ((t (:foreground "#9893a5"))))
 '(font-lock-doc-markup-face ((t (:foreground "#56949f"))))
 '(font-lock-keyword-face ((t (:foreground "#907aa9"))))
 '(font-lock-string-face ((t (:foreground "#618774"))))
 '(font-lock-builtin-face ((t (:foreground "#b4637a"))))
 '(font-lock-constant-face ((t (:foreground "#ca6e69"))))
 '(font-lock-function-name-face ((t (:foreground "#295e73"))))
 '(font-lock-function-call-face ((t (:foreground "#295e73"))))
 '(font-lock-variable-name-face ((t (:foreground "#575279"))))
 '(font-lock-variable-use-face ((t (:foreground "#575279"))))
 '(font-lock-type-face ((t (:foreground "#ea9d34"))))
 '(font-lock-number-face ((t (:foreground "#ea9d34"))))
 '(font-lock-symbol-face ((t (:foreground "#56949f"))))
 '(font-lock-property-face ((t (:foreground "#56949f"))))
 '(font-lock-operator-face ((t (:foreground "#a8a3b3"))))
 '(font-lock-punctuation-face ((t (:foreground "#a8a3b3"))))
 '(font-lock-delimiter-face ((t (:foreground "#a8a3b3"))))
 '(font-lock-bracket-face ((t (:foreground "#a8a3b3"))))
 '(font-lock-regexp-face ((t (:foreground "#dd9024"))))
 '(font-lock-escape-face ((t (:foreground "#ca6e69"))))
 '(font-lock-preprocessor-face ((t (:foreground "#816b9a"))))
 '(font-lock-negation-char-face ((t (:foreground "#ea9d34"))))
 '(font-lock-warning-face ((t (:foreground "#ea9d34"))))
 '(isearch ((t (:background "#b8cece" :foreground "#575279"))))
 '(lazy-highlight ((t (:background "#d0d8d8"))))
 '(match ((t (:background "#d0d8d8"))))
 '(completions-annotations ((t (:foreground "#a8a3b3"))))
 '(vertico-current ((t (:background "#b8cece" :foreground "#575279"))))
 '(vertico-group-title ((t (:foreground "#4c4769" :bold t))))
 '(vertico-group-separator ((t (:foreground "#9893a5" :strike-through t))))
 '(corfu-default ((t (:background "#ebe5df" :foreground "#575279"))))
 '(corfu-current ((t (:background "#d0d8d8"))))
 '(corfu-annotations ((t (:foreground "#a8a3b3"))))
 '(consult-preview-line ((t (:background "#d0d8d8"))))
 '(mode-line ((t (:background "#ebe5df" :foreground "#625c87"))))
 '(mode-line-inactive ((t (:background "#ebe5df" :foreground "#bdbfc9"))))
 '(header-line ((t (:background "#ebe5df" :foreground "#625c87"))))
 '(tab-bar ((t (:background "#faf4ed" :foreground "#9893a5"))))
 '(tab-bar-tab ((t (:background "#faf4ed" :foreground "#575279" :bold t))))
 '(tab-bar-tab-inactive ((t (:background "#faf4ed" :foreground "#a8a3b3"))))
 '(which-key-key-face ((t (:foreground "#286983" :bold t))))
 '(which-key-group-title-face ((t (:foreground "#907aa9"))))
 '(which-key-command-description-face ((t (:foreground "#575279"))))
 '(flymake-error ((t (:underline (:style wave :color "#b4637a")))))
 '(flymake-warning ((t (:underline (:style wave :color "#ea9d34")))))
 '(flymake-note ((t (:underline (:style wave :color "#618774")))))
 '(eglot-highlight-symbol-face ((t (:background "#b8cece"))))
 '(show-paren-match ((t (:background "#b8cece" :bold t))))
 '(show-paren-mismatch ((t (:background "#b4637a" :foreground "#faf4ed"))))
 '(diff-hl-change ((t (:foreground "#ea9d34" :background "#ebdfe4"))))
 '(diff-hl-delete ((t (:foreground "#b4637a" :background "#ebdfe4"))))
 '(diff-hl-insert ((t (:foreground "#618774" :background "#ebdfe4"))))
 '(diff-added ((t (:foreground "#618774"))))
 '(diff-removed ((t (:foreground "#b4637a"))))
 '(diff-changed ((t (:foreground "#ea9d34"))))
 '(magit-section-highlight ((t (:background "#ebdfe4"))))
 '(magit-section-heading ((t (:foreground "#907aa9" :bold t))))
 '(magit-diff-added ((t (:foreground "#618774"))))
 '(magit-diff-removed ((t (:foreground "#b4637a")))))

(provide-theme 'dawnfox)

