;;; nightfox-theme.el --- Nightfox dark theme (Nightfox family port) -*- lexical-binding: t; -*-

;;; Port of EdenEast/nightfox.nvim's Nightfox palette.
;;; Colors come from lua/nightfox/palette/nightfox.lua upstream.

;;; ---- Nightfox: dark ----

(deftheme nightfox "Nightfox family (nvim port): Nightfox dark.")

(custom-theme-set-faces 'nightfox
 '(default ((t (:background "#192330" :foreground "#cdcecf"))))
 '(cursor ((t (:background "#9d79d6"))))
 '(region ((t (:background "#2b3b51" :foreground "#aeafb0"))))
 '(hl-line ((t (:background "#29394f"))))
 '(line-number ((t (:background "#192330" :foreground "#71839b"))))
 '(line-number-current-line ((t (:background "#29394f" :foreground "#cdcecf"))))
 '(fringe ((t (:background "#192330" :foreground "#71839b"))))
 '(vertical-border ((t (:background "#192330" :foreground "#39506d"))))
 '(window-divider ((t (:foreground "#39506d"))))
 '(shadow ((t (:foreground "#71839b"))))
 '(minibuffer-prompt ((t (:foreground "#d6d6d7"))))
 '(error ((t (:foreground "#c94f6d"))))
 '(warning ((t (:foreground "#dbc074"))))
 '(success ((t (:foreground "#81b29a"))))
 '(font-lock-comment-face ((t (:foreground "#738091"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#738091"))))
 '(font-lock-doc-face ((t (:foreground "#738091"))))
 '(font-lock-doc-markup-face ((t (:foreground "#63cdcf"))))
 '(font-lock-keyword-face ((t (:foreground "#9d79d6"))))
 '(font-lock-string-face ((t (:foreground "#81b29a"))))
 '(font-lock-builtin-face ((t (:foreground "#c94f6d"))))
 '(font-lock-constant-face ((t (:foreground "#d08855"))))
 '(font-lock-function-name-face ((t (:foreground "#5c9ed6"))))
 '(font-lock-function-call-face ((t (:foreground "#5c9ed6"))))
 '(font-lock-variable-name-face ((t (:foreground "#cdcecf"))))
 '(font-lock-variable-use-face ((t (:foreground "#cdcecf"))))
 '(font-lock-type-face ((t (:foreground "#dbc074"))))
 '(font-lock-number-face ((t (:foreground "#f4a261"))))
 '(font-lock-symbol-face ((t (:foreground "#63cdcf"))))
 '(font-lock-property-face ((t (:foreground "#63cdcf"))))
 '(font-lock-operator-face ((t (:foreground "#71839b"))))
 '(font-lock-punctuation-face ((t (:foreground "#71839b"))))
 '(font-lock-delimiter-face ((t (:foreground "#71839b"))))
 '(font-lock-bracket-face ((t (:foreground "#71839b"))))
 '(font-lock-regexp-face ((t (:foreground "#c5aa53"))))
 '(font-lock-escape-face ((t (:foreground "#d08855"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8f6dae"))))
 '(font-lock-negation-char-face ((t (:foreground "#f4a261"))))
 '(font-lock-warning-face ((t (:foreground "#dbc074"))))
 '(isearch ((t (:background "#3c5372" :foreground "#cdcecf"))))
 '(lazy-highlight ((t (:background "#2b3b51"))))
 '(match ((t (:background "#2b3b51"))))
 '(completions-annotations ((t (:foreground "#71839b"))))
 '(vertico-current ((t (:background "#3c5372" :foreground "#cdcecf"))))
 '(vertico-group-title ((t (:foreground "#d6d6d7" :bold t))))
 '(vertico-group-separator ((t (:foreground "#738091" :strike-through t))))
 '(corfu-default ((t (:background "#131a24" :foreground "#cdcecf"))))
 '(corfu-current ((t (:background "#2b3b51"))))
 '(corfu-annotations ((t (:foreground "#71839b"))))
 '(consult-preview-line ((t (:background "#2b3b51"))))
 '(mode-line ((t (:background "#131a24" :foreground "#71839b"))))
 '(mode-line-inactive ((t (:background "#131a24" :foreground "#71839b"))))
 '(header-line ((t (:background "#131a24" :foreground "#aeafb0"))))
 '(tab-bar ((t (:background "#192330" :foreground "#738091"))))
 '(tab-bar-tab ((t (:background "#192330" :foreground "#cdcecf" :bold t))))
 '(tab-bar-tab-inactive ((t (:background "#192330" :foreground "#71839b"))))
 '(which-key-key-face ((t (:foreground "#719cd6" :bold t))))
 '(which-key-group-title-face ((t (:foreground "#9d79d6"))))
 '(which-key-command-description-face ((t (:foreground "#cdcecf"))))
 '(flymake-error ((t (:underline (:style wave :color "#c94f6d")))))
 '(flymake-warning ((t (:underline (:style wave :color "#dbc074")))))
 '(flymake-note ((t (:underline (:style wave :color "#81b29a")))))
 '(eglot-highlight-symbol-face ((t (:background "#3c5372"))))
 '(show-paren-match ((t (:background "#3c5372" :bold t))))
 '(show-paren-mismatch ((t (:background "#c94f6d" :foreground "#192330"))))
 '(diff-hl-change ((t (:foreground "#dbc074" :background "#29394f"))))
 '(diff-hl-delete ((t (:foreground "#c94f6d" :background "#29394f"))))
 '(diff-hl-insert ((t (:foreground "#81b29a" :background "#29394f"))))
 '(diff-added ((t (:foreground "#81b29a"))))
 '(diff-removed ((t (:foreground "#c94f6d"))))
 '(diff-changed ((t (:foreground "#dbc074"))))
 '(magit-section-highlight ((t (:background "#29394f"))))
 '(magit-section-heading ((t (:foreground "#9d79d6" :bold t))))
 '(magit-diff-added ((t (:foreground "#81b29a"))))
 '(magit-diff-removed ((t (:foreground "#c94f6d")))))

(provide-theme 'nightfox)

;;; nightfox-family-themes.el ends here
